### ISSUE TITLE
Vertical window resize image issue

### ISSUE THREAD

**Issue by mattcanty** [ChangoMan/gatsby-starter-strata#6]
I am not sure how to fix this but I have this problem with my website at the moment. Only the image I use is much narrower so therefore is more apparent.

<img width="688" alt="image" src="https://user-images.githubusercontent.com/2089581/75279427-805dd280-5803-11ea-8833-6b621ddb7e82.png">

**Comment by arthurgeron** [comment]
You need to post more details, what's the resolution of the screen used? What browser did you use? Giving a repository that replicates this issue should help as well.

**Comment by mattcanty** [comment]
Good point @arthurgeron.

To reproduce:
1. Go to https://mattcanty.com/
2. Resize window vertically

Probably not a huge problem, who resizes their window whilst browsing anyway. But interested to know if there might be a way of mainting the image size and position.

Source: https://github.com/mattcanty/mattcanty.com

**Comment by arthurgeron** [comment]
Thank you for the example! The issue resides in `#header`'s `background-size` css attribute, when you set it to `auto, auto 100%` instead of just `auto, auto` the browser will always force it to always try to fit the entire dimension of that element, which means when you resize it vertically the height will be smaller than the image's making it shrink.

Changing `background-size` to `auto,auto;` solves the issue.

**Comment by mattcanty** [comment]
Thanks @arthurgeron. The fix is alredy live. Happy to close 😄
